split, subsString, charAt 메서드 테스트 완료 하였습니다.
ChangSubKwak/java-racingcar pull request #1
Opened 2021-09-23 07:16 UTC by hosuhosoo

성공 코드 작성은 큰 어려움 없이 잘 해결 하였습니다.
실패코드 작성시 Exception 발생시켜 오류 확인 까지는 큰 무리 없이 하였습니다만 assertThatThrownBy메서드 이용하여 실패코드 를 통과시키는 과정에서 아직 isInstanceOf의 활용 부분에서 헤메었습니다. jUnit관련 메서드에 아직 익숙치 않아 좀더 연구를 요해야 할것 같습니다. 하지만 테스트코드 작성의 의도는 파악하기 시작하여 큰 도움이 되었습니다.
TDD방식에 좀더 흥미를 가지게 되는 계기가 되었습니다 ^^
마지막으로 gitbash 관련 명령어들이 아직 미숙하여 시간을 낭비하기도 했습니다. 좀더  적응하도록 노력하겠습니다.

2021-09-24 13:17 UTC, ChangSubKwak requested changes
제가 커멘트 하면 수정할 부분은 수정하시고, 그리고 의견이 있으면 커멘트 달아주면 저도 거기에 커멘트를 다는 방식으로 커뮤니케이션이 하면 될 것 같습니다. 그리고 커멘트에 대해서 수정이 완료되면 제가 머지하는 방식으로 진행할 예정입니다. 

그리고 머지가 완료되면 다음과제를 주는 방식으로 갈 예정이에요. 그런데 이번에는 과제양이 많지 않으니 수정요청과 동시에 과제를 드릴께요. (과제를 드리는 방법은 따로 이야기 드릴께요)

앞으로 부족하지만 제가 가지고 있는 지식중에서 높은 퀄리티의 것을 전달하려고 노력해볼께요. 리뷰 내용이 답이 되는 내용도 있지만 스타일이나 또는 저도 누군가의 좋은 방법을 보고 배운 것이니 그대로 따라가도 나쁘지는 않을 것이라는 생각이 들어요. 그럼 파이팅!

2021-09-24 13:17 UTC, ChangSubKwak commented on src/test/java/StringTest.java
> +        //assertThat("1,2".split(",")).containsExactly("1","2");
이 주석은 의미가 없어보여서 삭제해도 좋을 것 같아요.

2021-09-24 13:17 UTC, ChangSubKwak commented on src/test/java/StringTest.java
> +    void substringTest() {
@DisplayName을 써서 어떤 테스트를 의미하는지 설명을 하면 좋을 것 같아요.
테스트 자체로 별도의 문서 없이 설계 문서 역할을 할 수도 있거든요.

2021-09-24 13:17 UTC, ChangSubKwak commented on src/test/java/StringTest.java
> +        String a = "(1,2)";
변수가 무엇을 의미하는지를 변수명만 보고 알 수 있도록 작성하면 보기 좋은 코드가 됩니다.
한번 시도해보세요. 그러면 작성한 코드에 대해서 시간이 지날수록 뿌듯함을 느낄 수 있을꺼에요.

2021-09-24 13:17 UTC, ChangSubKwak commented on src/test/java/StringTest.java
> +        int target2 = a.indexOf(")");
이것도 이런 식으로 명명해보면 읽기에는 좋은 코드가 됩니다. (변수명이 길어도 상관없어요)
```suggestion
        int positionOfLeftBracket = a.indexOf("(");
        int positionOfRightBracket = a.indexOf(")");
```

2021-09-24 13:17 UTC, ChangSubKwak commented on src/test/java/StringTest.java
> +    }
assertThat를 이용한 구문이 없네요. 테스트를 위한 구문을 작성해보세요.

2021-09-24 13:17 UTC, ChangSubKwak commented on src/test/java/StringTest.java
> +    @DisplayName("문자열 abc에 대해 charAt메서드를 사용하여 범위가벗어나게 index를 설정 하면 StringIndexOutOfBoundsException이 발생된다")
@Display를 이용한 설명 작성 좋습니다. 👍 
귀찮을 수 있지만, 모든 테스트에 설명글을 적어 놓으면 그 자체로 좋은 문서가 됩니다. 😄

2021-09-24 13:17 UTC, ChangSubKwak commented on src/test/java/StringTest.java
> +    }
테스트 코드 작성 잘하셨습니다. 앞으로 모든 코드는 이렇게 작성하면 됩니다.

2021-09-26 14:08 UTC, hosuhosoo commented on src/test/java/StringTest.java
> +    }
제가 assertThat 을 이용한 구문의 코드작성 의도를 파악을 못했었습니다. 
StringIndexOutOfBoundsException테스트코드 관련하여서만 하는건줄 알고 다른 실패코드는 작성할 생각을 안했었네요 ㅜ 좋은지적 감사합니다 ! ㅎㅎ

2021-09-26 14:10 UTC, hosuhosoo commented on src/test/java/StringTest.java
> +        String a = "(1,2)";
단지 결과값에만 급급하여 습관처럼 작성해 나갔네요... 사소한거 하나라도 누구라도 보면 알수있게끔 변수명 등을 명명하여 작성하는 습관을 들이도록 하겠습니다^^

2021-09-26 14:14 UTC, hosuhosoo commented on src/test/java/StringTest.java
> +    void substringTest() {
설계 문서 역할도 가능하다고 하시니 어떤 의도인지 바로 파악 되었습니다. 
앞으로 테스트 자체로 문서화도 가능한점 유의 하겠습니다^^

2021-09-29 09:05 UTC, merged