Test : SetTest관련 요구사항 완료 하였습니다 ^^
ChangSubKwak/java-racingcar pull request #2
Opened 2021-10-01 00:24 UTC by hosuhosoo

요구사항 1,2에 대하여 전의 과제와 비슷한 경험으로 큰어려움이 없었습니다.

요구사항3에  @CsvSource 를 이용하여 실패코드 작성하는 부분에서  @CsvSource에 대해 개념이 확실히 이해가 되지않았습니다.

 @CsvSource이용한 코드에 대해 크게 만족하지 못했습니다 ㅠㅠ 혹  더 괜찮은 과정이 있었을거 같은데 피드백 부탁드립니다.

2021-10-01 11:15 UTC, ChangSubKwak requested changes
모르면 고민의 시간을 갖는 것은 중요한데요.
대신 그 고민의 시간이 길어지는 것도 좋지 않다고 생각해요.
고민을 최대한 해보고 안되면 힌트라도 달라고 하는 것도 방법이에요. 
그럼 파이팅

2021-10-01 11:15 UTC, ChangSubKwak commented on src/test/java/SetTest.java
> +    }
[캠퍼스 핵데이 Java 코딩 컨벤션]에 "8.1. 공백으로 줄을 끝내지 않음"을 참고하여 제거해보세요.

2021-10-01 11:15 UTC, ChangSubKwak commented on src/test/java/SetTest.java
> +    }
이 부분도 위에서 위에서 언급한 것과 동일하게 의미없는 공백을 제거해보세요.

2021-10-01 11:15 UTC, ChangSubKwak commented on src/test/java/SetTest.java
> +    }
의미 없는 공백을 제거하고 함수의 indent를 맞추는 것도 고려해보세요.
그리고 assertTrue와 assertFalse를 이용하여 테스트 코드를 작성하였는데요.
assertThat과 isEqualTo를 사용하여 굳이 if문 사용안하고 한줄로 만들 수 있어요.
한 번 고민해 보세요.

2021-10-02 09:27 UTC, hosuhosoo commented on src/test/java/SetTest.java
> +    }
캠퍼스 핵데이 Java 코딩 컨벤션 보면서 신경 쓰겠습니다 !

2021-10-02 09:27 UTC, hosuhosoo commented on src/test/java/SetTest.java
> +    }
수정하였습니다 ㅎㅎ

2021-10-02 09:28 UTC, hosuhosoo commented on src/test/java/SetTest.java
> +    }
결국 도움받아서 해결은 하였지만 어떤식으로 생각하여 접근하여야 하는지 알게되었습니다 감사합니다!

2021-10-02 12:27 UTC, ChangSubKwak commented
함수 하나에 대해서만 indent 맞추어 주시면 될 것 같아요. 그래서 이번 PR은 머지를 진행하도록 할께요.
수고하셨습니다. 조금씩 알아가는 재미가 있겠지만 잘 모르는 부분도 있을 텐데요.
이번 처럼 질문하면 제가 힌트를 주면서 해결해가면, 앞으로도 충분히 할 수 있을 것 입니다. ^^
파이팅.

2021-10-02 12:27 UTC, merged