문자열 계산기 테스트 PR요청입니다.
ChangSubKwak/java-racingcar pull request #3
Opened 2021-10-18 04:49 UTC by hosuhosoo

프로덕션 코드 작성은 큰 어려움 없이 사칙연산 단위별로 로직을 구성하였습니다. 입력값에 따른 결과값이 나오는걸 확인 하였고 사칙연산 계산에 맞게끔 결과도 출력되는걸 확인 하였습니다.
테스트 코드를 구현하는데 있어서는 조금 헤메어서 도움을 받아 해결 하였습니다.
연산을 하는 테스트코드는 비교적 쉽게 하였으나 공백이 오는 익셉션 등을 해결하는 능력에 있어 아직 람다식 표현 방법이 익숙하지 않았습니다.
코드를 많이 줄일수 있는 람다식 표현법에 좀더 익숙해지기 위해 다시 한번 소스를 보며 적응 해나가겠습니다.

2021-10-20 04:14 UTC, ChangSubKwak requested changes
일단 스타일에 대해서 주로 언급을 했는데요.
스타일은 인텔리제이의 "Reformat Code"을 사용하는 것을 추천드려요.
그리고 코드 컨벤션과 관련하여 인텔리제이에 세팅하여 저장시 자동 변경되도록 해보세요.
(참고 : https://naver.github.io/hackday-conventions-java/#_intellij)

2021-10-20 04:14 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +        }catch (Exception e){
중괄호 다음에 공백을 넣어 주면 좋을 것 같아요.
다음과 같은 컨벤션을 확인해보세요.(https://naver.github.io/hackday-conventions-java/  의 8.3)

2021-10-20 04:14 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +            System.out.println("0으로는 나누어지지 않습니다."); //0으로 나누어지지않는 부분 Exception 처리
문자열을 출력하는 대신 예외를 던져야 겠죠?

2021-10-20 04:14 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +            return divide(first, second);
이 부분도 중괄호 추가를 하면 좋을 것 같아요.
참고(https://naver.github.io/hackday-conventions-java/#need-braces)

2021-10-20 04:14 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +        else System.out.println("잘못된 값 입니다");
else문이 필요한지 한 번 고려해보세요.

2021-10-20 04:14 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +        throw new RuntimeException();
예외가 어떤 의미인지를 알려주는 예외를 사용하고 메시지도 작성하면 좋을 것 같아요.

2021-10-20 04:14 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +    public String[] space(String str){
함수의 네이밍에 대해서 다시 생각해보면 좋을 것 같아요. (동사 + 명사)

2021-10-20 04:14 UTC, ChangSubKwak commented on src/test/java/CalcuratorTest.java
> +        assertThat(0).isEqualTo(calculator.divide(8,0));
0으로 나눌 경우 예외를 던지고 0을 반환하는 것이 맞는지 고려해보면 좋을 것 같아요. 
0을 반환하면 0 / 10  = 10 / 0 과 같은 결과가 나오지 않을까요?

2021-10-20 04:14 UTC, ChangSubKwak commented on src/test/java/StringTest.java
> +
공백도 무엇인가를 의미할 수 있어서 필요 없다면 제거해보는 것도 좋을 것 같아요.

2021-10-22 07:57 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +        }catch (Exception e){
중괄호 다음 공백을 넣었습니다.
 인텔리제이의 "Reformat Code"을 사용을 추천 해주셔서 진행 하였고 추후 DeskTop에도 세팅을 하겠습니다^^

2021-10-22 07:58 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +            System.out.println("0으로는 나누어지지 않습니다."); //0으로 나누어지지않는 부분 Exception 처리
ArithmeticException이 발생하는 것을 확인하여 ArithmeticException을 예외처리 하여  나누기가 안된다는 것을 출력 하게끔 수정하였습니다.

2021-10-22 07:58 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +            return divide(first, second);
완료 하였습니다^^

2021-10-22 07:59 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +        else System.out.println("잘못된 값 입니다");
불필요한 else문을 제거 하였습니다^^

2021-10-22 08:00 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +        throw new RuntimeException();
RuntimeException 의 종류를 정의하여 Exception의 종류를 메세지로 출력 하는 방향으로 해야하는지요??

2021-10-22 08:00 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +    public String[] space(String str){
함수 네이밍 수정 완료하였습니다.
앞으로는 네이밍 룰에 맞게 좀더 함수명에 신경 쓰는 습관을 익히 겠습니다!!

2021-10-22 08:01 UTC, hosuhosoo commented on src/test/java/CalcuratorTest.java
> +        assertThat(0).isEqualTo(calculator.divide(8,0));
0으로 나누어지지 않을때의 경우만 예외처리를 하여 0을 반환하게끔 수정 하였습니다.

2021-10-22 08:01 UTC, hosuhosoo commented on src/test/java/StringTest.java
> +
알려주셨던 부분인데 놓쳤던거 같습니다. 코드작성 할떄 주의깊게 집중하도록 하겠습니다 ㅎㅎ

2021-10-22 08:08 UTC, hosuhosoo commented
이번 과제로 여러파일을 한꺼번에 git add 작업을 통하여 stage에 add할수 있는 방법을 찾아보았습니다.
폴더 단위로 add를 하여 편하게 add, commit, push 를 할수 있었습니다!

2021-10-25 00:09 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +        throw new RuntimeException();
"예외", "커스터마이징" 등으로 검색하면 개발자 자신만의 예외를 만드는 것에 대한 정보를 얻을 수 있어요.

2021-10-25 00:55 UTC, ChangSubKwak commented on src/test/java/CalcuratorTest.java
> +        assertThat(0).isEqualTo(calculator.divide(8,0));
저의 의도가 약간 원하는 바대로 전달이 되지 않은 것 같아요.
0으로 나누어지지 않을 때만 예외처리를 하여  0을 반환하는 것이 어떤 처리를 위한 것인지 궁금해요.

2021-10-25 05:01 UTC, ChangSubKwak requested changes
이제는 git 사용에도 많이 익숙해진 것 같아요.
공백이 8자리가 된 것은, 인텔리 제이의 Settings-Editor-Code Style-Java에서 Use tab character 체크박스 버튼을 해제하면 잘 보일꺼에요.

2021-10-25 05:01 UTC, ChangSubKwak commented on src/test/java/CalcuratorTest.java
> +	}
메서드의 첫글자는 소문자로 하는 것을 관용적으로 하니까 변경하는 것을 고려해보세요.

2021-10-25 05:01 UTC, ChangSubKwak commented on src/test/java/CalcuratorTest.java
> +        }).withMessage("/ by zero");
네, 잘하셨습니다. 예외 테스트는 이렇게 하시면 됩니다.

2021-10-25 05:01 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +	}
이 부분을 enum을 이용해서 if문을 제거해보도록 해보세요.

2021-10-28 12:18 UTC, ChangSubKwak requested changes
스타일 적용을 잘하셨어요. 리뷰어의 관점에서 소프트탭을 사용하면 환경과 관계없이 일정한 공간이 유지되어, 배려받는 느낌이 있습니다.

enum 클래스는 만들어 놓고, 정작 Calculator클래스에서 calculate 메서드내부의 if문은 제거는 하지 않았네요. if문을 제거시도를 해보세요.

그리고 해결이 된 comment나 수정요청이 아닌 comment에 대해서는 "Resolve conversation"을 눌러서 완료 처리 하면 좋을 것 같아요.

다음 단계까지 얼마 남지가 않았어요. 파이팅

2021-10-28 12:18 UTC, ChangSubKwak commented on src/test/java/CalcuratorTest.java
>  	}
enum에 대한 테스트를 잘 작성하셨네요.
다만 공백 처리가 안된 것 같네요. Reformat Code가 이 코드에 대해서는 수행되지 않은 것 같아요.
체크 한번 해보시면 될 것 같습니다.

2021-10-28 12:18 UTC, ChangSubKwak commented on src/main/java/work3/Operator.java
> +    PLUS("+", (firstNumber, secondNumber) -> firstNumber + secondNumber),
`(firstNumber, secondNumber) -> firstNumber + secondNumber`부분을 Math 클래스의 정적함수인 addExact를 메서드 참조 표현을 이용하여 Math::addExact 로 표현도 가능하니 참고해보세요. (4칙연산에 대한 메서드가 다 존재합니다.)

2021-10-28 12:18 UTC, ChangSubKwak commented on src/main/java/work3/Operator.java
> +    }
calculate의 인자의 타입을 Wrapper 클래스로 한 이유가 있는지 궁금해요. calculate함수를 호출할 때, 정수값을 받으면 boxing될 것이고, 객체가 만들어 지면서 HEAP메모리를 사용하게 되요. 그런데 primitive 타입(int)을 사용하면 STACK메모리을 사용하기 때문에, 불필요한 boxing과정이 없을 것이고 STACK메모리를 사용하기에 속도면에서도 유리할 수 있어요.
지금은 간단한 코드라서 별 문제 없지만, 프로그램이 커지게 될 경우, 다른 이야기가 될 수 있어요. 처음부터 좋은 습관을 들이면 좋을 것 같아서 이야기 드려보았어요.

2021-10-28 12:18 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +    }
이 부분은 위의 공백 나누기 함수와, Operator 클래스를 이용하면 코드가 조금은 심플해질 것 같아요.

2021-10-28 12:18 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +    }
변수 result를 지역변수로 둔 이유가 있는지 궁금해요. 
result를 클래스 변수로 선언하고 calculate함수내에서 계산하고 result로 저장하면 굳이 반환하여 result를 저장하지 않아도 될 것 같아요.

2021-10-29 02:34 UTC, hosuhosoo commented on src/test/java/CalcuratorTest.java
>  	}
Reformat Code 를 실행시켰습니다. 이제는 단축키를 활용하여 익숙하게 사용할수 있을거같습니다.

2021-10-29 02:35 UTC, hosuhosoo commented on src/main/java/work3/Operator.java
> +    PLUS("+", (firstNumber, secondNumber) -> firstNumber + secondNumber),
Math 클래스의  사칙연산을 확인 하였습니다 ^^

2021-10-29 02:37 UTC, hosuhosoo commented on src/main/java/work3/Operator.java
> +    }
Wrapper타입의 Integer를 기본타입의 int형으로 수정 하였습니다. 사소하다고 생각했던 부분이 설명을 듣고 중요하다는 것을 인지 하였습니다. 앞으로 습관을 잘 들여보도록 노력하겠습니다.

2021-10-29 02:38 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +    }
result를 지역변수로 두고 for분이 돌때마다 결과값을 더해서 결과를 산출한다고 생각하고 그렇게 진행 하였습니다.
그리고 Operato클래스를 이용하여 코드를 한번 수정해보았습니다^^

2021-11-05 06:48 UTC, hosuhosoo commented on src/test/java/CalcuratorTest.java
> +	}
수정 완료하였습니다 ㅎㅎ

2021-11-05 06:48 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +	}
enum을 이용하여 제거하여 사용하지 않으므로 삭제 처리 하였습니다.

2021-11-05 06:49 UTC, hosuhosoo commented on src/main/java/work3/Calculator.java
> +        throw new RuntimeException();
enum을 이용하여 if문을 삭제하는 과정에서 해당 로직은 삭제처리 하였습니다. 하지만 어떤 의도로 예외처리를 하는지 인지하였고 숙지 하였습니다.

2021-11-08 01:13 UTC, ChangSubKwak approved these changes
네, 노력한 흔적이 보여서 저도 보람이 생깁니다. 
앞으로 조금씩, 가랑비에 속옷 젖듯이 꾸준히 진행하면, 자신도 모르게 성장해 있을 것 입니다.
이번에는 merge하도록 하겠습니다.
수고하셨습니다.

2021-11-08 01:13 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> -	}
네, if 지옥을 잘 제거하고 아래에서 Operator 열거 클래스를 이용하여 깔끔해진 것을 확인하실 수 있을 꺼에요. 👍

2021-11-08 01:13 UTC, ChangSubKwak commented on src/main/java/work3/Calculator.java
> +    }
네, 잘하셨습니다. 😃 
나중에는 for문에서 i를 2씩 증가시키지 않고, 연산자와 숫자를 하나로 추상화한 클래스를 이용하면 for문 대신 이 클래스를 객체를 stream형식으로 변경한다면 for문도 제거 가능할 겁니다.

이 부분은 추후에 한 번 도전 해보는 것을 추천드려요. 💯

2021-11-08 01:13 UTC, merged