자동차경주 테스트코드 작성 피드백 요청드립니다.
ChangSubKwak/java-racingcar pull request #4
Opened 2022-01-21 09:09 UTC by hosuhosoo

한동안 코드작성에 있어서 시간을 투자하지 못하여 프로덕션코드에 대해서 완료후 테스트 코드 작성에 어려움을 느꼈습니다.

리뷰어님 말씀처럼 미흡하더라도 피드백을 먼저 받아야할거 같아서 이렇게 요청드립니다.

인뷰, 리절트뷰, 를 따로 작성 하였고 자동차라는 객체를 따로 생성하는것이 맞다고 판단되었습니다.

테스트 코드에는 요청사항에 모든 메서드에 테스트코드가 작성 되어야 한다는 부분이 시간을 많이 잡았던거 같습니다. 아직 테스트 코드 작성이 미흡하여 피드백 받은후 다시금 작성 하는게 맞는거 같아 이렇게 요청 드립니다.!

2022-01-21 09:42 UTC, ChangSubKwak commented on src/main/java/racing/InputView.java
> +        Scanner scanner = new Scanner(System.in);
getEventInfo가 호출될 때 마다, Scanner 객체가 생성될텐데요. 
만약 수천번 호출되면, 수천번만큼의 Scanner 객체가 생성될 텐데요. 
호출될 떄 마다, 이미 생성된 Scanner 객체를 활용할 수 있도록 고민요청드려요.

2022-01-21 09:43 UTC, ChangSubKwak commented on src/main/java/racing/Main.java
> +        }
indent 가 2단계 이네요. 1로 줄여주세요.

2022-01-21 09:46 UTC, ChangSubKwak commented on src/main/java/racing/InputView.java
> +    private int tryCount;
변수 선언 없이, 입력 받는 방법을 생각해보세요.

2022-01-25 05:54 UTC, ChangSubKwak requested changes
메시지를 나누어서 커밋 요청 부탁드려요.
그리고, 수정이 완료된 커멘트에 대해서는 "Resolve conversation" 버튼을 눌러주세요.
오랜만에 Pull Request 해주시느라 고생하셨어요. 👍 
커맨트에 대해서 수정해주시고 다시 커밋 부탁드릴께요. 😃

2022-01-25 05:54 UTC, ChangSubKwak commented on src/main/java/racing/InputView.java
> +package racing;
패키지명도 고민을 해보시는 것을 추천드려요.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/test/java/racingTest/RacingTest.java
> +package racingTest;
패키지 명에 대해서 수정을 고민해보세요.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/test/java/racingTest/RacingTest.java
> +    }
이 코드는 테스트가 안될 것 같습니다.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/test/java/racingTest/RacingTest.java
> +
삭제 요청 드립니다.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/test/java/racingTest/RacingTest.java
> +        assertThat(racingEvent.getCarList().size()).isEqualTo(carCount);
디미터의 법칙을 준수하도록 코드를 수정해주세요.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/test/java/racingTest/RacingTest.java
>      }
어떤 테스트 인지 판별되지 않네요. 명확한 테스트 케이스를 작성해 주세요.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/main/java/racing/Cars.java
>      private ArrayList<Integer> position;
position 이라는 것 자체를 클래스로 만들어 보면 어떨까요?
position이라는 것에 대해서 예외처리도 별도로 할 수 있고 역할을 분리 시킬 수 있어서 장점이 많습니다.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/main/java/racing/InputView.java
> +    public static  int getCarCount(){
static 와 int 사이에 공백이 2칸이네요. 수정해 주세요.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/main/java/racing/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
scanner 변수를 static final 로 선언 잘 하셨네요. 👍

2022-01-25 05:54 UTC, ChangSubKwak commented on src/main/java/racing/Main.java
> +    private static void checkCars(RacingEvent racingEvent, ResultView resultView, int i) {
resultView 변수는 인자로 받을 필요가 있을까요?
함수의 인자를 줄이는 것도 리팩토링 하는 것이라고 생각해주세요.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/main/java/racing/RacingEvent.java
> +                cars.moveForward(new RandomMove().move());
이렇게 하면 cars의 객체 개수 만큼 new RandomMove()을 계속적으로 호출하게 되는데요.
최초 한 번만 설정한 뒤, 이동하는 방법은 없는지 생각해보는 것을 추천드려요.

2022-01-25 05:54 UTC, ChangSubKwak commented on src/main/java/racing/ResultView.java
>              System.out.print("-");
"-"도 상수로 정의해보세요.

2022-01-27 01:25 UTC, hosuhosoo commented on src/main/java/racing/InputView.java
> +package racing;
변경 하였습니다.

2022-01-28 04:21 UTC, ChangSubKwak requested changes
지난 번 요청사항을 1개 빼고 전부 해주셨네요. 고생하셨어요.
새롭게 작성한 부분에, 수정할 부분과 지난번 커멘트 드렸던 원시값 포장 관련, 작성후 다시 요청 부탁드려요.
그리고 여러번 이야기 했던 부분인데, 커밋 메시지의 룰을 지켜주세요. 
(https://velog.io/@outstandingboy/Git-%EC%BB%A4%EB%B0%8B-%EB%A9%94%EC%8B%9C%EC%A7%80-%EA%B7%9C%EC%95%BD-%EC%A0%95%EB%A6%AC-the-AngularJS-commit-conventions)

2022-01-28 04:21 UTC, ChangSubKwak commented on src/main/java/racing/Main.java
> +    }
Controller 레이어에 View 레이어 관련 코드가 보이네요. View 레이어로 옮겨주세요.

2022-01-28 04:21 UTC, ChangSubKwak commented on src/main/java/racing/domain/Cars.java
> +    private ArrayList<Integer> position;
다음의 링크를 참고하여
https://livenow14.tistory.com/37
position 값을 별도의 클래스로 정의해보세요.

2022-01-28 04:21 UTC, ChangSubKwak commented on src/main/java/racing/domain/RacingEvent.java
> +        }
indent가 2네요. indent를 1로 만들어보는 것을 추천드려요.

2022-01-28 04:21 UTC, ChangSubKwak commented on src/main/java/racing/domain/RandomMove.java
> +        return 4 <= random.nextInt(10);
4와 10도 상수로 정의할 수 있지 않을까요?

2022-01-28 04:21 UTC, ChangSubKwak commented on src/test/java/racing/RacingTest.java
> +        int size = racingEvent.getCarList().size();
디미터의 법칙을 지켜주세요.

2023-02-10 12:05 UTC, merged